export const MAX_WORDS = 70;
export const REPO_NAME = 'octotype'
export const LABEL = 'published'
export const EXAMPLE_PATH = 'blog-starter'
export const CMS_NAME = 'GitHub Issues'
export const HOME_OG_IMAGE_URL = 'https://octotype.vercel.app/assets/blog/preview/cover.jpg'
export const USE_OPEN_AI=false
export const MINIMALIST="minimalist"
export const MAGAZINE="magazine"
export const RAW_URL="https://raw.githubusercontent.com"
export const CONFIG_FILE="main/config.json"